package com.example.worktracker.common

object Constants {
    //screens
    const val HOME: String = "Home"
    const val CONTRIBUTORS: String = "Contributors"
    const val STATUSES: String = "Statuses"
    const val PRIORITIES: String = "Priorities"
    const val WORK_TYPES: String = "Work Types"
    const val WORK_TYPE: String = "Work Type"
    const val ABOUT: String = "About"

    //actions
    const val GET_CONTRIBUTORS_ACTION: String = "getContributors"
    const val ADD_CONTRIBUTOR_ACTION: String = "addContributor"
    const val UPDATE_CONTRIBUTOR_ACTION: String = "updateContributor"
    const val DELETE_CONTRIBUTOR_ACTION: String = "deleteContributor"
    const val GET_WORK_TYPES_ACTION: String = "getWorkTypes"
    const val ADD_WORK_TYPE_ACTION: String = "addWorkType"
    const val UPDATE_WORK_TYPE_ACTION: String = "updateWorkType"
    const val DELETE_WORK_TYPE_ACTION: String = "deleteWorkType"
    const val GET_STATUSES_ACTION: String = "getStatuses"
    const val ADD_STATUS_ACTION: String = "addStatus"
    const val UPDATE_STATUS_ACTION: String = "updateStatus"
    const val DELETE_STATUS_ACTION: String = "deleteStatus"
    const val GET_PRIORITIES_ACTION: String = "getPriorities"
    const val ADD_PRIORITY_ACTION: String = "addPriority"
    const val UPDATE_PRIORITY_ACTION: String = "updatePriority"
    const val DELETE_PRIORITY_ACTION: String = "deletePriority"
    const val GET_WORK_ITEMS_ACTION: String = "getWorkItems"
    const val ADD_WORK_ITEM_ACTION: String = "addWorkItem"
    const val UPDATE_WORK_ITEM_ACTION: String = "updateWorkItem"



    const val BUGS: String = "Bugs"
    const val EDIT_CONTRIBUTOR: String = "edit contributor"
    const val EDIT_STATUS: String = "edit status"
    const val EDIT_PRIORITY: String = "edit priority"
    const val EDIT_WORK_TYPE: String = "edit work type"
    const val ADD_CONTRIBUTOR: String = "Add contributor"
    const val ADD_STATUS: String = "Add status"
    const val ADD_PRIORITY: String = "Add priority"
    const val ADD_WORK_TYPE: String = "Add work type"
    const val UPDATE_CONTRIBUTOR: String = "Update contributor"
    const val UPDATE_STATUS: String = "Update status"
    const val UPDATE_PRIORITY: String = "Update priority"
    const val UPDATE_WORK_TYPE: String = "Update work type"
    const val CONTRIBUTOR_DETAILS: String = "Contributor Details"
    const val STATUS_DETAILS: String = "Status Details"
    const val PRIORITY_DETAILS: String = "Priority Details"
    const val WORK_TYPE_DETAILS: String = "Work Type Details"
    const val DELETE_CONTRIBUTOR: String = "Delete Contributor"
    const val DELETE_STATUS: String = "Delete Status"
    const val DELETE_PRIORITY: String = "Delete Priority"
    const val DELETE_WORK_TYPE: String = "Delete work type"
    const val ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_CONTRIBUTOR: String = "Are you sure you want to delete this contributor"
    const val ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_STATUS: String = "Are you sure you want to delete this status"
    const val ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_PRIORITY: String = "Are you sure you want to delete this priority"
    const val ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_WORK_TYPE: String = "Are you sure you want to delete this work type"
    const val WORK_ITEM_TITLE: String = "Work Item Title"
    const val WORK_ITEM_DESCRIPTION: String = "Work Item Description"
    const val ADD_WORK_ITEM: String = "Add Work Item"
    const val NAME: String = "Name: "
    const val DASHBOARD: String = "Dashboard"
    const val WORK_TRACKER: String = "Work Tracker"
    const val CREATED_AT: String = "Created at: "
    const val UPDATED_AT: String = "Updated at: "
    const val NAME_CAN_NOT_BE_EMPTY: String = "name can not  be empty"
    const val CONTRIBUTOR_IS_ADDED_SUCCESSFULLY: String = "Contributed is added successfully"
    const val CONTRIBUTOR_IS_UPDATED_SUCCESSFULLY: String = "Contributed is updated successfully"
    const val CONTRIBUTOR_IS_DELETED_SUCCESSFULLY: String = "Contributed is deleted successfully"
    const val STATUS_IS_ADDED_SUCCESSFULLY: String = "Status is added successfully"
    const val STATUS_IS_UPDATED_SUCCESSFULLY: String = "Status is updated successfully"
    const val STATUS_IS_DELETED_SUCCESSFULLY: String = "Status is deleted successfully"
    const val PRIORITY_IS_ADDED_SUCCESSFULLY: String = "Priority is added successfully"
    const val PRIORITY_IS_UPDATED_SUCCESSFULLY: String = "Priority is updated successfully"
    const val PRIORITY_IS_DELETED_SUCCESSFULLY: String = "Priority is deleted successfully"
    const val WORK_TYPE_IS_ADDED_SUCCESSFULLY: String = "Work type is added successfully"
    const val WORK_TYPE_IS_UPDATED_SUCCESSFULLY: String = "Work type is updated successfully"
    const val WORK_TYPE_IS_DELETED_SUCCESSFULLY: String = "Work type is deleted successfully"
    const val ADD: String = "Add"
    const val UPDATE: String = "Update"
    const val CANCEL: String = "[ Cancel ]"
    const val DELETE: String = "Delete"
    const val CONTRIBUTOR_NAME: String = "Contributor name"
    const val STATUS_NAME: String = "Status name"
    const val PRIORITY_NAME: String = "Priority name"
    const val WORK_TYPE_NAME: String = "Work type name"
    const val LOOKS_EMPTY_HERE: String = "Looks empty here"
    const val ASSIGNED_TO: String = "Assigned to: "
    const val ASSIGNEE: String = "Assignee"
    const val ASSIGNER: String = "Assigner"
    const val STATUS: String = "Status"
    const val PRIORITY: String = "Priority"


    const val BASE_URL="https://script.google.com/macros/s/AKfycbwFQ_CrF2p4rkINqIDA4Ks8recXGEz263rZietoEPc4G2l6jl65n4PivhHn4ZPZOa0W-A/"

    const val CLOUD_NAME="drnwo9mdm"
    const val API_KEY="817135666282944"
    const val API_SECRET="WxI-NHr1ZwemgHF5hki-FWQL620"
}